AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: HelloWorldLambdaJava

Resources:

  HelloWorldLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HelloWorldJava
      Runtime: java8
      MemorySize: 512
      Handler: book.StringIntegerBooleanLambda::handlerInt
      CodeUri: target/lambda.jar
      Environment:
        Variables:
          DATABASE_URL: example-database-url
